--gmltest
--gml written by GopherAtl
--lua auto-generated by gmlc
--A test program for the GML gui library
local gml=require("gml")

local testgui,button2,scrollH,button1,label1,listbox1,scrollV,label2,field1,setLabelToScroll

testgui = gml.create("center","center",32,19)
button2 = testgui:addButton(-4,6,10,1,"Close",testgui.close)
scrollH = testgui:addScrollBarH(1,-1,29,100,setLabelToScroll)
button1 = testgui:addButton(4,6,10,1,"Toggle",function()
      if label1.visible then
        label1:hide()
      else
        label1:show()
      end
    end)
label1 = testgui:addLabel("center",2,13,"Hello, World!")
listbox1 = testgui:addListBox("center",8,16,8,{"one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty","twenty-one","twenty-two","twenty-three","twenty-four","twenty-five"})
scrollV = testgui:addScrollBarV(-1,1,16,100,setLabelToScroll)
label2 = testgui:addLabel(-2,-2,7,"label2")
field1 = testgui:addTextField("center",4,18,"")

function setLabelToScroll()
  label2.text=string.format("%3s,%3s",scrollH.scrollPos,scrollV.scrollPos)
  label2:draw()
end

testgui:addHandler("key_down",
    function(event,addy,char,key)
      --ctrl-r
      if char==18 then
        local fg,bg=component.gpu.getForeground(), component.gpu.getBackground()
        label["text-color"]=math.random(0,0xffffff)
        label1:draw()
        component.gpu.setForeground(fg)
        component.gpu.setBackground(bg)
      end
    end
)

label1:hide()
label2.text="  0,  0"

testgui:run()